### ISSUE TITLE
博客接口

### ISSUE THREAD

**Issue by MagginZ** [gotoxu/blog#1]
获取文章列表接口
发布文章的接口
登录接口

**Comment by gotoxu** [comment]
@MagginZ  发布文章的时候，你请求参数中传递的文章内容是原生markdown语法的，还是转换成html语法的，也即是否需要服务端将markdown语法的内容转换成html语法？

**Comment by MagginZ** [comment]
@gotoxu 点击发布文章内容转化成了html语法。接口可以写个接口文档

**Comment by gotoxu** [comment]
@MagginZ 经过考虑，前段向后段提交参数时还是传递原生的markdown内容，后端返回给前端仍然返回原生markdown内容，由前端自行解析成html并显示

**Comment by MagginZ** [comment]
@gotoxu 好的

**Comment by gotoxu** [comment]
@MagginZ 周五前提交接口文档和后台Docker镜像
